# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20170504_1051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeSteps',
            new_name='RecipeStep',
        ),
        migrations.RenameModel(
            old_name='RecipeStepsIngredients',
            new_name='RecipeStepIngredient',
        ),
    ]
